export const PG_KEYWORDS = [
  // Standard
  "SELECT",
  "FROM",
  "WHERE",
  "JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "INNER JOIN",
  "FULL OUTER JOIN",
  "CROSS JOIN",
  "ON",
  "GROUP BY",
  "ORDER BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "INSERT INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE FROM",
  "CREATE TABLE",
  "DROP TABLE",
  "ALTER TABLE",
  "TRUNCATE",
  "AND",
  "OR",
  "NOT",
  "IN",
  "LIKE",
  "ILIKE",
  "BETWEEN",
  "IS NULL",
  "IS NOT NULL",
  "EXISTS",
  "DISTINCT",
  "AS",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "UNION",
  "UNION ALL",
  "INTERSECT",
  "EXCEPT",
  "WITH",
  "RETURNING",

  // PostgreSQL specific
  "RETURNING",
  "ON CONFLICT",
  "DO NOTHING",
  "DO UPDATE",
  "LATERAL",
  "FILTER",
  "OVER",
  "PARTITION BY",
  "WINDOW",
  "GENERATED ALWAYS AS",
  "NULLS FIRST",
  "NULLS LAST",
  "ASC",
  "DESC",
  "EXPLAIN",
  "EXPLAIN ANALYZE",
  "VACUUM",
  "ANALYZE",
  "COPY",
  "LISTEN",
  "NOTIFY",
];

export interface PgFunction {
  label: string;
  insertText: string;
  detail: string;
  category: string;
  description: string;
  signature: string;
  returns: string;
}

export const PG_FUNCTIONS: PgFunction[] = [
  // ── Aggregate ────────────────────────────────────────────────────────────
  {
    label: "COUNT",
    insertText: "COUNT(${1:*})",
    detail: "→ bigint",
    category: "Aggregate",
    description: "Count the number of rows or non-null values.",
    signature: "COUNT(*) / COUNT(expr)",
    returns: "bigint",
  },
  {
    label: "SUM",
    insertText: "SUM(${1:expr})",
    detail: "→ numeric",
    category: "Aggregate",
    description: "Sum all non-null values.",
    signature: "SUM(expr)",
    returns: "numeric",
  },
  {
    label: "AVG",
    insertText: "AVG(${1:expr})",
    detail: "→ numeric",
    category: "Aggregate",
    description: "Compute the arithmetic average of non-null values.",
    signature: "AVG(expr)",
    returns: "numeric",
  },
  {
    label: "MAX",
    insertText: "MAX(${1:expr})",
    detail: "→ same type",
    category: "Aggregate",
    description: "Return the maximum value of a set.",
    signature: "MAX(expr)",
    returns: "same type as input",
  },
  {
    label: "MIN",
    insertText: "MIN(${1:expr})",
    detail: "→ same type",
    category: "Aggregate",
    description: "Return the minimum value of a set.",
    signature: "MIN(expr)",
    returns: "same type as input",
  },
  {
    label: "ARRAY_AGG",
    insertText: "ARRAY_AGG(${1:expr})",
    detail: "→ array",
    category: "Aggregate",
    description: "Collect all non-null values into an array.",
    signature: "ARRAY_AGG(expr [ORDER BY ...])",
    returns: "anyarray",
  },
  {
    label: "STRING_AGG",
    insertText: "STRING_AGG(${1:expr}, '${2:,}')",
    detail: "→ text",
    category: "Aggregate",
    description: "Concatenate non-null values joined by a delimiter.",
    signature: "STRING_AGG(expr, delimiter)",
    returns: "text",
  },
  {
    label: "JSON_AGG",
    insertText: "JSON_AGG(${1:expr})",
    detail: "→ json",
    category: "Aggregate",
    description: "Aggregate values as a JSON array.",
    signature: "JSON_AGG(expr)",
    returns: "json",
  },
  {
    label: "JSONB_AGG",
    insertText: "JSONB_AGG(${1:expr})",
    detail: "→ jsonb",
    category: "Aggregate",
    description: "Aggregate values as a JSONB array.",
    signature: "JSONB_AGG(expr)",
    returns: "jsonb",
  },
  {
    label: "BOOL_AND",
    insertText: "BOOL_AND(${1:expr})",
    detail: "→ boolean",
    category: "Aggregate",
    description: "Return true if all input values are true.",
    signature: "BOOL_AND(expr)",
    returns: "boolean",
  },
  {
    label: "BOOL_OR",
    insertText: "BOOL_OR(${1:expr})",
    detail: "→ boolean",
    category: "Aggregate",
    description: "Return true if at least one input value is true.",
    signature: "BOOL_OR(expr)",
    returns: "boolean",
  },

  // ── Window ────────────────────────────────────────────────────────────────
  {
    label: "ROW_NUMBER",
    insertText: "ROW_NUMBER() OVER (${1:partition})",
    detail: "Window function",
    category: "Window",
    description:
      "Assign a unique sequential integer to each row within a partition.",
    signature: "ROW_NUMBER() OVER ([PARTITION BY ...] ORDER BY ...)",
    returns: "bigint",
  },
  {
    label: "RANK",
    insertText: "RANK() OVER (${1:partition})",
    detail: "Window function",
    category: "Window",
    description:
      "Rank rows with gaps for ties (same rank = same value, next rank skips).",
    signature: "RANK() OVER ([PARTITION BY ...] ORDER BY ...)",
    returns: "bigint",
  },
  {
    label: "DENSE_RANK",
    insertText: "DENSE_RANK() OVER (${1:partition})",
    detail: "Window function",
    category: "Window",
    description:
      "Like RANK() but without gaps — ties share rank, next is rank+1.",
    signature: "DENSE_RANK() OVER ([PARTITION BY ...] ORDER BY ...)",
    returns: "bigint",
  },
  {
    label: "LAG",
    insertText: "LAG(${1:expr}, ${2:1}) OVER (${3:partition})",
    detail: "Window function",
    category: "Window",
    description: "Access a value from a previous row without a self-join.",
    signature: "LAG(expr [, offset [, default]]) OVER (...)",
    returns: "same type as expr",
  },
  {
    label: "LEAD",
    insertText: "LEAD(${1:expr}, ${2:1}) OVER (${3:partition})",
    detail: "Window function",
    category: "Window",
    description: "Access a value from a following row without a self-join.",
    signature: "LEAD(expr [, offset [, default]]) OVER (...)",
    returns: "same type as expr",
  },
  {
    label: "FIRST_VALUE",
    insertText: "FIRST_VALUE(${1:expr}) OVER (${2:partition})",
    detail: "Window function",
    category: "Window",
    description: "Return the first value in the window frame.",
    signature: "FIRST_VALUE(expr) OVER (...)",
    returns: "same type as expr",
  },
  {
    label: "LAST_VALUE",
    insertText: "LAST_VALUE(${1:expr}) OVER (${2:partition})",
    detail: "Window function",
    category: "Window",
    description: "Return the last value in the window frame.",
    signature: "LAST_VALUE(expr) OVER (...)",
    returns: "same type as expr",
  },
  {
    label: "NTILE",
    insertText: "NTILE(${1:n}) OVER (${2:partition})",
    detail: "Window function",
    category: "Window",
    description: "Divide rows into n roughly equal groups (buckets).",
    signature: "NTILE(n) OVER ([PARTITION BY ...] ORDER BY ...)",
    returns: "bigint",
  },

  // ── String ────────────────────────────────────────────────────────────────
  {
    label: "CONCAT",
    insertText: "CONCAT(${1:str1}, ${2:str2})",
    detail: "→ text",
    category: "String",
    description: "Concatenate values. NULL arguments are ignored.",
    signature: "CONCAT(str1, str2, ...)",
    returns: "text",
  },
  {
    label: "UPPER",
    insertText: "UPPER(${1:text})",
    detail: "→ text",
    category: "String",
    description: "Convert string to upper-case.",
    signature: "UPPER(text)",
    returns: "text",
  },
  {
    label: "LOWER",
    insertText: "LOWER(${1:text})",
    detail: "→ text",
    category: "String",
    description: "Convert string to lower-case.",
    signature: "LOWER(text)",
    returns: "text",
  },
  {
    label: "TRIM",
    insertText: "TRIM(${1:text})",
    detail: "→ text",
    category: "String",
    description: "Remove leading and trailing whitespace (or specified chars).",
    signature: "TRIM([LEADING|TRAILING|BOTH] [chars FROM] text)",
    returns: "text",
  },
  {
    label: "LTRIM",
    insertText: "LTRIM(${1:text})",
    detail: "→ text",
    category: "String",
    description: "Remove leading whitespace or specified characters.",
    signature: "LTRIM(text [, chars])",
    returns: "text",
  },
  {
    label: "RTRIM",
    insertText: "RTRIM(${1:text})",
    detail: "→ text",
    category: "String",
    description: "Remove trailing whitespace or specified characters.",
    signature: "RTRIM(text [, chars])",
    returns: "text",
  },
  {
    label: "LENGTH",
    insertText: "LENGTH(${1:text})",
    detail: "→ int",
    category: "String",
    description: "Return the number of characters in the string.",
    signature: "LENGTH(text)",
    returns: "int",
  },
  {
    label: "SUBSTRING",
    insertText: "SUBSTRING(${1:text} FROM ${2:1} FOR ${3:5})",
    detail: "→ text",
    category: "String",
    description: "Extract a substring using SQL standard syntax or regex.",
    signature: "SUBSTRING(text FROM start [FOR length])",
    returns: "text",
  },
  {
    label: "REPLACE",
    insertText: "REPLACE(${1:text}, ${2:from}, ${3:to})",
    detail: "→ text",
    category: "String",
    description: "Replace all occurrences of a substring.",
    signature: "REPLACE(text, from, to)",
    returns: "text",
  },
  {
    label: "SPLIT_PART",
    insertText: "SPLIT_PART(${1:text}, '${2:,}', ${3:1})",
    detail: "→ text",
    category: "String",
    description:
      "Split a string by a delimiter and return the nth field (1-indexed).",
    signature: "SPLIT_PART(text, delimiter, n)",
    returns: "text",
  },
  {
    label: "REGEXP_MATCH",
    insertText: "REGEXP_MATCH(${1:text}, '${2:pattern}')",
    detail: "→ text[]",
    category: "String",
    description:
      "Match a POSIX regular expression pattern and return captures.",
    signature: "REGEXP_MATCH(text, pattern [, flags])",
    returns: "text[]",
  },
  {
    label: "REGEXP_REPLACE",
    insertText: "REGEXP_REPLACE(${1:text}, '${2:pattern}', '${3:replacement}')",
    detail: "→ text",
    category: "String",
    description: "Replace matches of a POSIX regex pattern.",
    signature: "REGEXP_REPLACE(text, pattern, replacement [, flags])",
    returns: "text",
  },
  {
    label: "FORMAT",
    insertText: "FORMAT('${1:%s}', ${2:arg})",
    detail: "→ text",
    category: "String",
    description:
      "Format arguments according to a format string (printf-style).",
    signature: "FORMAT(formatstr, arg [, ...])",
    returns: "text",
  },
  {
    label: "LPAD",
    insertText: "LPAD(${1:text}, ${2:length}, ${3: })",
    detail: "→ text",
    category: "String",
    description: "Left-pad a string to a given length with a fill character.",
    signature: "LPAD(text, length [, fill])",
    returns: "text",
  },
  {
    label: "RPAD",
    insertText: "RPAD(${1:text}, ${2:length}, ${3: })",
    detail: "→ text",
    category: "String",
    description: "Right-pad a string to a given length with a fill character.",
    signature: "RPAD(text, length [, fill])",
    returns: "text",
  },

  // ── Date / Time ───────────────────────────────────────────────────────────
  {
    label: "NOW",
    insertText: "NOW()",
    detail: "→ timestamptz",
    category: "Date/Time",
    description: "Return the current transaction start time (with time zone).",
    signature: "NOW()",
    returns: "timestamptz",
  },
  {
    label: "CURRENT_DATE",
    insertText: "CURRENT_DATE",
    detail: "→ date",
    category: "Date/Time",
    description: "Return the current date (no time zone).",
    signature: "CURRENT_DATE",
    returns: "date",
  },
  {
    label: "CURRENT_TIME",
    insertText: "CURRENT_TIME",
    detail: "→ timetz",
    category: "Date/Time",
    description: "Return the current time of day (with time zone).",
    signature: "CURRENT_TIME",
    returns: "timetz",
  },
  {
    label: "CURRENT_TIMESTAMP",
    insertText: "CURRENT_TIMESTAMP",
    detail: "→ timestamptz",
    category: "Date/Time",
    description: "Return the current date and time (with time zone).",
    signature: "CURRENT_TIMESTAMP",
    returns: "timestamptz",
  },
  {
    label: "DATE_TRUNC",
    insertText: "DATE_TRUNC('${1:day}', ${2:timestamp})",
    detail: "→ timestamp",
    category: "Date/Time",
    description:
      "Truncate a timestamp to the specified precision (year, month, day, hour, …).",
    signature: "DATE_TRUNC(field, source [, timezone])",
    returns: "timestamp / timestamptz",
  },
  {
    label: "DATE_PART",
    insertText: "DATE_PART('${1:epoch}', ${2:timestamp})",
    detail: "→ float8",
    category: "Date/Time",
    description: "Extract a date/time sub-field as a number.",
    signature: "DATE_PART(field, source)",
    returns: "float8",
  },
  {
    label: "EXTRACT",
    insertText: "EXTRACT(${1:YEAR} FROM ${2:timestamp})",
    detail: "→ numeric",
    category: "Date/Time",
    description:
      "SQL-standard equivalent of DATE_PART. Extracts a sub-field from a timestamp or interval.",
    signature: "EXTRACT(field FROM source)",
    returns: "numeric",
  },
  {
    label: "AGE",
    insertText: "AGE(${1:timestamp1}, ${2:timestamp2})",
    detail: "→ interval",
    category: "Date/Time",
    description:
      "Compute the difference between two timestamps as a human-readable interval.",
    signature: "AGE(timestamp1 [, timestamp2])",
    returns: "interval",
  },
  {
    label: "TO_TIMESTAMP",
    insertText: "TO_TIMESTAMP(${1:text}, '${2:YYYY-MM-DD}')",
    detail: "→ timestamptz",
    category: "Date/Time",
    description: "Convert a string to a timestamp using a format pattern.",
    signature: "TO_TIMESTAMP(text, format)",
    returns: "timestamptz",
  },
  {
    label: "TO_DATE",
    insertText: "TO_DATE('${1:text}', '${2:YYYY-MM-DD}')",
    detail: "→ date",
    category: "Date/Time",
    description: "Convert a string to a date using a format pattern.",
    signature: "TO_DATE(text, format)",
    returns: "date",
  },
  {
    label: "MAKE_DATE",
    insertText: "MAKE_DATE(${1:year}, ${2:month}, ${3:day})",
    detail: "→ date",
    category: "Date/Time",
    description: "Construct a date from year, month, and day fields.",
    signature: "MAKE_DATE(year, month, day)",
    returns: "date",
  },
  {
    label: "INTERVAL",
    insertText: "INTERVAL '${1:1 day}'",
    detail: "interval literal",
    category: "Date/Time",
    description: "A time span literal (e.g. '1 day', '2 hours 30 minutes').",
    signature: "INTERVAL 'text'",
    returns: "interval",
  },

  // ── JSON / JSONB ──────────────────────────────────────────────────────────
  {
    label: "TO_JSON",
    insertText: "TO_JSON(${1:value})",
    detail: "→ json",
    category: "JSON",
    description: "Convert any SQL value to JSON.",
    signature: "TO_JSON(value)",
    returns: "json",
  },
  {
    label: "TO_JSONB",
    insertText: "TO_JSONB(${1:value})",
    detail: "→ jsonb",
    category: "JSON",
    description: "Convert any SQL value to JSONB (binary JSON).",
    signature: "TO_JSONB(value)",
    returns: "jsonb",
  },
  {
    label: "JSON_BUILD_OBJECT",
    insertText: "JSON_BUILD_OBJECT('${1:key}', ${2:value})",
    detail: "→ json",
    category: "JSON",
    description: "Build a JSON object from key-value pairs.",
    signature: "JSON_BUILD_OBJECT(key, value [, ...])",
    returns: "json",
  },
  {
    label: "JSONB_BUILD_OBJECT",
    insertText: "JSONB_BUILD_OBJECT('${1:key}', ${2:value})",
    detail: "→ jsonb",
    category: "JSON",
    description: "Build a JSONB object from key-value pairs.",
    signature: "JSONB_BUILD_OBJECT(key, value [, ...])",
    returns: "jsonb",
  },
  {
    label: "JSON_ARRAY_LENGTH",
    insertText: "JSON_ARRAY_LENGTH(${1:json})",
    detail: "→ int",
    category: "JSON",
    description: "Return the number of elements in a top-level JSON array.",
    signature: "JSON_ARRAY_LENGTH(json)",
    returns: "int",
  },
  {
    label: "JSONB_SET",
    insertText: "JSONB_SET(${1:target}, '{${2:key}}', ${3:value})",
    detail: "→ jsonb",
    category: "JSON",
    description:
      "Return a JSONB value with the sub-object at the path replaced or inserted.",
    signature: "JSONB_SET(target, path, new_value [, create_missing])",
    returns: "jsonb",
  },
  {
    label: "JSON_EXTRACT_PATH",
    insertText: "JSON_EXTRACT_PATH(${1:json}, '${2:key}')",
    detail: "→ json",
    category: "JSON",
    description:
      "Equivalent to the #> operator — extract a sub-object at the given path.",
    signature: "JSON_EXTRACT_PATH(json, path_elem [, ...])",
    returns: "json",
  },

  // ── Type Casting / Conversion ─────────────────────────────────────────────
  {
    label: "CAST",
    insertText: "CAST(${1:value} AS ${2:type})",
    detail: "Type cast",
    category: "Conversion",
    description:
      "Convert a value to a different data type. Equivalent to value::type.",
    signature: "CAST(value AS type)",
    returns: "target type",
  },
  {
    label: "COALESCE",
    insertText: "COALESCE(${1:value1}, ${2:value2})",
    detail: "First non-null",
    category: "Conversion",
    description:
      "Return the first non-null argument. Useful for replacing NULLs with defaults.",
    signature: "COALESCE(val1, val2, ...)",
    returns: "same type as args",
  },
  {
    label: "NULLIF",
    insertText: "NULLIF(${1:value1}, ${2:value2})",
    detail: "NULL if equal",
    category: "Conversion",
    description:
      "Return NULL if value1 equals value2, otherwise return value1.",
    signature: "NULLIF(value1, value2)",
    returns: "same type as value1",
  },
  {
    label: "GREATEST",
    insertText: "GREATEST(${1:val1}, ${2:val2})",
    detail: "Max of list",
    category: "Conversion",
    description:
      "Return the largest value from a list of expressions (NULLs are ignored).",
    signature: "GREATEST(val1, val2, ...)",
    returns: "same type as args",
  },
  {
    label: "LEAST",
    insertText: "LEAST(${1:val1}, ${2:val2})",
    detail: "Min of list",
    category: "Conversion",
    description:
      "Return the smallest value from a list of expressions (NULLs are ignored).",
    signature: "LEAST(val1, val2, ...)",
    returns: "same type as args",
  },
  {
    label: "TO_CHAR",
    insertText: "TO_CHAR(${1:value}, '${2:FM9999}')",
    detail: "→ text",
    category: "Conversion",
    description: "Convert a number or timestamp to a formatted text string.",
    signature: "TO_CHAR(value, format)",
    returns: "text",
  },
  {
    label: "TO_NUMBER",
    insertText: "TO_NUMBER('${1:text}', '${2:9999}')",
    detail: "→ numeric",
    category: "Conversion",
    description: "Convert a formatted text string to a numeric value.",
    signature: "TO_NUMBER(text, format)",
    returns: "numeric",
  },

  // ── Array ─────────────────────────────────────────────────────────────────
  {
    label: "ARRAY_LENGTH",
    insertText: "ARRAY_LENGTH(${1:array}, ${2:1})",
    detail: "→ int",
    category: "Array",
    description:
      "Return the length of the requested array dimension (1-indexed).",
    signature: "ARRAY_LENGTH(array, dimension)",
    returns: "int",
  },
  {
    label: "ARRAY_APPEND",
    insertText: "ARRAY_APPEND(${1:array}, ${2:element})",
    detail: "→ array",
    category: "Array",
    description: "Append an element to the end of an array.",
    signature: "ARRAY_APPEND(array, element)",
    returns: "anyarray",
  },
  {
    label: "ARRAY_PREPEND",
    insertText: "ARRAY_PREPEND(${1:element}, ${2:array})",
    detail: "→ array",
    category: "Array",
    description: "Prepend an element to the beginning of an array.",
    signature: "ARRAY_PREPEND(element, array)",
    returns: "anyarray",
  },
  {
    label: "UNNEST",
    insertText: "UNNEST(${1:array})",
    detail: "Expand array to rows",
    category: "Array",
    description: "Expand an array to a set of rows (one row per element).",
    signature: "UNNEST(array)",
    returns: "setof anyelement",
  },
  {
    label: "ARRAY_TO_STRING",
    insertText: "ARRAY_TO_STRING(${1:array}, '${2:,}')",
    detail: "→ text",
    category: "Array",
    description: "Concatenate array elements into a string with a delimiter.",
    signature: "ARRAY_TO_STRING(array, delimiter [, null_string])",
    returns: "text",
  },

  // ── Math ──────────────────────────────────────────────────────────────────
  {
    label: "ABS",
    insertText: "ABS(${1:value})",
    detail: "→ numeric",
    category: "Math",
    description: "Return the absolute value of a number.",
    signature: "ABS(x)",
    returns: "numeric",
  },
  {
    label: "ROUND",
    insertText: "ROUND(${1:value}, ${2:decimal})",
    detail: "→ numeric",
    category: "Math",
    description: "Round a number to the given number of decimal places.",
    signature: "ROUND(x [, decimal_places])",
    returns: "numeric",
  },
  {
    label: "CEIL",
    insertText: "CEIL(${1:value})",
    detail: "→ numeric",
    category: "Math",
    description: "Round up to the nearest integer.",
    signature: "CEIL(x)",
    returns: "numeric",
  },
  {
    label: "FLOOR",
    insertText: "FLOOR(${1:value})",
    detail: "→ numeric",
    category: "Math",
    description: "Round down to the nearest integer.",
    signature: "FLOOR(x)",
    returns: "numeric",
  },
  {
    label: "RANDOM",
    insertText: "RANDOM()",
    detail: "→ float8 [0,1)",
    category: "Math",
    description: "Return a random float uniformly distributed in [0.0, 1.0).",
    signature: "RANDOM()",
    returns: "float8",
  },
  {
    label: "GENERATE_SERIES",
    insertText: "GENERATE_SERIES(${1:start}, ${2:stop}, ${3:step})",
    detail: "Generate rows",
    category: "Math",
    description:
      "Generate a series of integer or timestamp values. Useful for range generation.",
    signature: "GENERATE_SERIES(start, stop [, step])",
    returns: "setof integer / timestamp",
  },
];

/** O(1) lookup map: uppercase label → PgFunction metadata */
export const PG_FUNCTION_MAP: Map<string, PgFunction> = new Map(
  PG_FUNCTIONS.map((f) => [f.label.toUpperCase(), f]),
);

export const PG_TYPES = [
  "INTEGER",
  "BIGINT",
  "SMALLINT",
  "SERIAL",
  "BIGSERIAL",
  "NUMERIC",
  "DECIMAL",
  "REAL",
  "DOUBLE PRECISION",
  "TEXT",
  "VARCHAR",
  "CHAR",
  "BPCHAR",
  "BOOLEAN",
  "DATE",
  "TIME",
  "TIMESTAMP",
  "TIMESTAMPTZ",
  "INTERVAL",
  "JSON",
  "JSONB",
  "UUID",
  "ARRAY",
  "BYTEA",
  "INET",
  "CIDR",
  "MACADDR",
  "TSVECTOR",
  "TSQUERY",
  "OID",
  "REGCLASS",
  "POINT",
  "LINE",
  "POLYGON",
];
